workflows:
  ios-workflow:
    name: Capacitor iOS Build

    environment:
      node: 22
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          npx cap sync ios

    artifacts:
      - ios/App/build/**/*.ipa

    publishing:
      email:
        recipients:
          - aramvoskanyan45@gmail.com